<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResumeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */



    public function run(): void
    {
        DB::table('resumes')->insert([
            [
                'ad_status'=>1,
                'user_id' => 2,
                'resume_name'=>'Горный инженер',
                'avatar'=>'avatar1.png',
                'email' => 'jobseeker1@example.com',
                'phone' => '123-456-7890',
                'location_id' => 1,
                'desired_salary' => 60000,
                'experience' => '3 года подземным горнорабочим, шахта им. А.Ф. Засядько',
                'education' => 'ДонНТУ\'СЗПСиГ 2016-2022',
                'about_me' => 'Трезв опрятен и плечист.',
                'category_id' => 1,
            ],
            [
                'ad_status'=>1,
                'user_id' => 2,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>1,
                'user_id' => 2,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>1,
                'user_id' => 4,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>1,
                'user_id' => 4,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>1,
                'user_id' => 4,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>2,
                'user_id' => 2,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>3,
                'user_id' => 2,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>4,
                'user_id' => 2,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>2,
                'user_id' => 4,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>3,
                'user_id' => 4,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>4,
                'user_id' => 4,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>2,
                'user_id' => 4,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            [
                'ad_status'=>3,
                'user_id' => 2,
                'resume_name'=>'Старший разработчик',
                'avatar'=>'avatar2.png',
                'email' => 'jobseeker2@example.com',
                'phone' => '987-654-3210',
                'location_id' => 2,
                'desired_salary' => 70000,
                'experience' => '5 years in full-stack development',
                'education' => 'Master\'s in Software Engineering',
                'about_me' => 'Full-stack developer with a focus on creating scalable and high-performance web apps.',
                'category_id' => 2,
            ],
            // Добавьте другие тестовые записи
        ]);
    }
}
